apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: patientservice-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: patient.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: patientservice
                port:
                  number: 80
