apiVersion: v1
kind: Service
metadata:
  name: patientservice
  labels:
    app: patientservice
spec:
  type: ClusterIP
  selector:
    app: patientservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
