apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: applicationservice-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: application.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: applicationservice
                port:
                  number: 80
