name: Deploy Backend Service

on:
  push:
    paths:
      - 'helm_backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: project-id-12345
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials gke-cluster-demo --region us-central1

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install backend ./helm_backend \
            --set image.repository=gcr.io/dev-repo/backendimage \
            --set image.tag=1.1
