name: Build and Push Docker Backend Image

on:
  push:
    branches:
      - Kishore-GCP   # run only when pushing to this branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: kish67/hackathon-usecase
          ref: Kishore-GCP

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t orderbackend:latest -f Dockerfile_orderservice .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name OrderService orderbackend:latest
